name: JavaScript CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Install dependencies
        run: npm install
        working-directory: /home/runner/work/Jiroes_portfolio/front

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest
        run: npm test
